/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLayoutImport } from './routes/auth/_layout'
import { Route as AppMRouteImport } from './routes/_app/m/route'
import { Route as AppDRouteImport } from './routes/_app/d/route'
import { Route as AppProfileIndexImport } from './routes/_app/profile/index'
import { Route as AuthLayoutRegisterImport } from './routes/auth/_layout/register'
import { Route as AuthLayoutLoginImport } from './routes/auth/_layout/login'
import { Route as AppMSettingsIndexImport } from './routes/_app/m/settings/index'
import { Route as AppMProfileIndexImport } from './routes/_app/m/profile/index'
import { Route as AppMNotificationsIndexImport } from './routes/_app/m/notifications/index'
import { Route as AppMLibraryIndexImport } from './routes/_app/m/library/index'
import { Route as AppMLectureHallIndexImport } from './routes/_app/m/lecture-hall/index'
import { Route as AppMHomeIndexImport } from './routes/_app/m/home/index'
import { Route as AppDSettingsIndexImport } from './routes/_app/d/settings/index'
import { Route as AppDProfileIndexImport } from './routes/_app/d/profile/index'
import { Route as AppDNotificationsIndexImport } from './routes/_app/d/notifications/index'
import { Route as AppDLibraryIndexImport } from './routes/_app/d/library/index'
import { Route as AppDLectureHallIndexImport } from './routes/_app/d/lecture-hall/index'
import { Route as AppDHomeIndexImport } from './routes/_app/d/home/index'
import { Route as AppMLibraryTalksIndexImport } from './routes/_app/m/library/talks/index'
import { Route as AppMLibraryPodcastsIndexImport } from './routes/_app/m/library/podcasts/index'
import { Route as AppMLibraryLecturesIndexImport } from './routes/_app/m/library/lectures/index'
import { Route as AppMLibraryImagesIndexImport } from './routes/_app/m/library/images/index'
import { Route as AppMLibraryBooksIndexImport } from './routes/_app/m/library/books/index'
import { Route as AppDLibraryPodcastsIndexImport } from './routes/_app/d/library/podcasts/index'
import { Route as AppDLibraryLecturesIndexImport } from './routes/_app/d/library/lectures/index'
import { Route as AppDLibraryImagesIndexImport } from './routes/_app/d/library/images/index'
import { Route as AppDLibraryBooksIndexImport } from './routes/_app/d/library/books/index'
import { Route as AppMLectureHallCourseCourseIdImport } from './routes/_app/m/lecture-hall/course/$courseId'
import { Route as AppDLectureHallCourseCourseIdImport } from './routes/_app/d/lecture-hall/course/$courseId'
import { Route as AppMHomeArticlesCategoryIdIndexImport } from './routes/_app/m/home/articles/$categoryId/index'
import { Route as AppDHomeArticlesCategoryIdIndexImport } from './routes/_app/d/home/articles/$categoryId/index'
import { Route as AppMLectureHallCourseLessonLessonIdImport } from './routes/_app/m/lecture-hall/course/lesson/$lessonId'
import { Route as AppMLectureHallCourseActivityActivityIdImport } from './routes/_app/m/lecture-hall/course/activity/$activityId'
import { Route as AppMHomeArticlesCategoryIdArticleIdImport } from './routes/_app/m/home/articles/$categoryId/$articleId'
import { Route as AppDLectureHallCourseLessonLessonIdImport } from './routes/_app/d/lecture-hall/course/lesson/$lessonId'
import { Route as AppDLectureHallCourseActivityActivityIdImport } from './routes/_app/d/lecture-hall/course/activity/$activityId'
import { Route as AppDHomeArticlesCategoryIdArticleIdImport } from './routes/_app/d/home/articles/$categoryId/$articleId'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AppMRouteRoute = AppMRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDRouteRoute = AppDRouteImport.update({
  id: '/d',
  path: '/d',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AuthLayoutRegisterRoute = AuthLayoutRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AppMSettingsIndexRoute = AppMSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMProfileIndexRoute = AppMProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMNotificationsIndexRoute = AppMNotificationsIndexImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMLibraryIndexRoute = AppMLibraryIndexImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMLectureHallIndexRoute = AppMLectureHallIndexImport.update({
  id: '/lecture-hall/',
  path: '/lecture-hall/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMHomeIndexRoute = AppMHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppDSettingsIndexRoute = AppDSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppDProfileIndexRoute = AppDProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppDNotificationsIndexRoute = AppDNotificationsIndexImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppDLibraryIndexRoute = AppDLibraryIndexImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppDLectureHallIndexRoute = AppDLectureHallIndexImport.update({
  id: '/lecture-hall/',
  path: '/lecture-hall/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppDHomeIndexRoute = AppDHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppMLibraryTalksIndexRoute = AppMLibraryTalksIndexImport.update({
  id: '/library/talks/',
  path: '/library/talks/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMLibraryPodcastsIndexRoute = AppMLibraryPodcastsIndexImport.update({
  id: '/library/podcasts/',
  path: '/library/podcasts/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMLibraryLecturesIndexRoute = AppMLibraryLecturesIndexImport.update({
  id: '/library/lectures/',
  path: '/library/lectures/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMLibraryImagesIndexRoute = AppMLibraryImagesIndexImport.update({
  id: '/library/images/',
  path: '/library/images/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppMLibraryBooksIndexRoute = AppMLibraryBooksIndexImport.update({
  id: '/library/books/',
  path: '/library/books/',
  getParentRoute: () => AppMRouteRoute,
} as any)

const AppDLibraryPodcastsIndexRoute = AppDLibraryPodcastsIndexImport.update({
  id: '/library/podcasts/',
  path: '/library/podcasts/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppDLibraryLecturesIndexRoute = AppDLibraryLecturesIndexImport.update({
  id: '/library/lectures/',
  path: '/library/lectures/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppDLibraryImagesIndexRoute = AppDLibraryImagesIndexImport.update({
  id: '/library/images/',
  path: '/library/images/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppDLibraryBooksIndexRoute = AppDLibraryBooksIndexImport.update({
  id: '/library/books/',
  path: '/library/books/',
  getParentRoute: () => AppDRouteRoute,
} as any)

const AppMLectureHallCourseCourseIdRoute =
  AppMLectureHallCourseCourseIdImport.update({
    id: '/lecture-hall/course/$courseId',
    path: '/lecture-hall/course/$courseId',
    getParentRoute: () => AppMRouteRoute,
  } as any)

const AppDLectureHallCourseCourseIdRoute =
  AppDLectureHallCourseCourseIdImport.update({
    id: '/lecture-hall/course/$courseId',
    path: '/lecture-hall/course/$courseId',
    getParentRoute: () => AppDRouteRoute,
  } as any)

const AppMHomeArticlesCategoryIdIndexRoute =
  AppMHomeArticlesCategoryIdIndexImport.update({
    id: '/home/articles/$categoryId/',
    path: '/home/articles/$categoryId/',
    getParentRoute: () => AppMRouteRoute,
  } as any)

const AppDHomeArticlesCategoryIdIndexRoute =
  AppDHomeArticlesCategoryIdIndexImport.update({
    id: '/home/articles/$categoryId/',
    path: '/home/articles/$categoryId/',
    getParentRoute: () => AppDRouteRoute,
  } as any)

const AppMLectureHallCourseLessonLessonIdRoute =
  AppMLectureHallCourseLessonLessonIdImport.update({
    id: '/lecture-hall/course/lesson/$lessonId',
    path: '/lecture-hall/course/lesson/$lessonId',
    getParentRoute: () => AppMRouteRoute,
  } as any)

const AppMLectureHallCourseActivityActivityIdRoute =
  AppMLectureHallCourseActivityActivityIdImport.update({
    id: '/lecture-hall/course/activity/$activityId',
    path: '/lecture-hall/course/activity/$activityId',
    getParentRoute: () => AppMRouteRoute,
  } as any)

const AppMHomeArticlesCategoryIdArticleIdRoute =
  AppMHomeArticlesCategoryIdArticleIdImport.update({
    id: '/home/articles/$categoryId/$articleId',
    path: '/home/articles/$categoryId/$articleId',
    getParentRoute: () => AppMRouteRoute,
  } as any)

const AppDLectureHallCourseLessonLessonIdRoute =
  AppDLectureHallCourseLessonLessonIdImport.update({
    id: '/lecture-hall/course/lesson/$lessonId',
    path: '/lecture-hall/course/lesson/$lessonId',
    getParentRoute: () => AppDRouteRoute,
  } as any)

const AppDLectureHallCourseActivityActivityIdRoute =
  AppDLectureHallCourseActivityActivityIdImport.update({
    id: '/lecture-hall/course/activity/$activityId',
    path: '/lecture-hall/course/activity/$activityId',
    getParentRoute: () => AppDRouteRoute,
  } as any)

const AppDHomeArticlesCategoryIdArticleIdRoute =
  AppDHomeArticlesCategoryIdArticleIdImport.update({
    id: '/home/articles/$categoryId/$articleId',
    path: '/home/articles/$categoryId/$articleId',
    getParentRoute: () => AppDRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_app/d': {
      id: '/_app/d'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof AppDRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/m': {
      id: '/_app/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof AppMRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_layout/login': {
      id: '/auth/_layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/register': {
      id: '/auth/_layout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthLayoutRegisterImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/d/home/': {
      id: '/_app/d/home/'
      path: '/home'
      fullPath: '/d/home'
      preLoaderRoute: typeof AppDHomeIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/lecture-hall/': {
      id: '/_app/d/lecture-hall/'
      path: '/lecture-hall'
      fullPath: '/d/lecture-hall'
      preLoaderRoute: typeof AppDLectureHallIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/library/': {
      id: '/_app/d/library/'
      path: '/library'
      fullPath: '/d/library'
      preLoaderRoute: typeof AppDLibraryIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/notifications/': {
      id: '/_app/d/notifications/'
      path: '/notifications'
      fullPath: '/d/notifications'
      preLoaderRoute: typeof AppDNotificationsIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/profile/': {
      id: '/_app/d/profile/'
      path: '/profile'
      fullPath: '/d/profile'
      preLoaderRoute: typeof AppDProfileIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/settings/': {
      id: '/_app/d/settings/'
      path: '/settings'
      fullPath: '/d/settings'
      preLoaderRoute: typeof AppDSettingsIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/m/home/': {
      id: '/_app/m/home/'
      path: '/home'
      fullPath: '/m/home'
      preLoaderRoute: typeof AppMHomeIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/lecture-hall/': {
      id: '/_app/m/lecture-hall/'
      path: '/lecture-hall'
      fullPath: '/m/lecture-hall'
      preLoaderRoute: typeof AppMLectureHallIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/library/': {
      id: '/_app/m/library/'
      path: '/library'
      fullPath: '/m/library'
      preLoaderRoute: typeof AppMLibraryIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/notifications/': {
      id: '/_app/m/notifications/'
      path: '/notifications'
      fullPath: '/m/notifications'
      preLoaderRoute: typeof AppMNotificationsIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/profile/': {
      id: '/_app/m/profile/'
      path: '/profile'
      fullPath: '/m/profile'
      preLoaderRoute: typeof AppMProfileIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/settings/': {
      id: '/_app/m/settings/'
      path: '/settings'
      fullPath: '/m/settings'
      preLoaderRoute: typeof AppMSettingsIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/d/lecture-hall/course/$courseId': {
      id: '/_app/d/lecture-hall/course/$courseId'
      path: '/lecture-hall/course/$courseId'
      fullPath: '/d/lecture-hall/course/$courseId'
      preLoaderRoute: typeof AppDLectureHallCourseCourseIdImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/m/lecture-hall/course/$courseId': {
      id: '/_app/m/lecture-hall/course/$courseId'
      path: '/lecture-hall/course/$courseId'
      fullPath: '/m/lecture-hall/course/$courseId'
      preLoaderRoute: typeof AppMLectureHallCourseCourseIdImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/d/library/books/': {
      id: '/_app/d/library/books/'
      path: '/library/books'
      fullPath: '/d/library/books'
      preLoaderRoute: typeof AppDLibraryBooksIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/library/images/': {
      id: '/_app/d/library/images/'
      path: '/library/images'
      fullPath: '/d/library/images'
      preLoaderRoute: typeof AppDLibraryImagesIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/library/lectures/': {
      id: '/_app/d/library/lectures/'
      path: '/library/lectures'
      fullPath: '/d/library/lectures'
      preLoaderRoute: typeof AppDLibraryLecturesIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/library/podcasts/': {
      id: '/_app/d/library/podcasts/'
      path: '/library/podcasts'
      fullPath: '/d/library/podcasts'
      preLoaderRoute: typeof AppDLibraryPodcastsIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/m/library/books/': {
      id: '/_app/m/library/books/'
      path: '/library/books'
      fullPath: '/m/library/books'
      preLoaderRoute: typeof AppMLibraryBooksIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/library/images/': {
      id: '/_app/m/library/images/'
      path: '/library/images'
      fullPath: '/m/library/images'
      preLoaderRoute: typeof AppMLibraryImagesIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/library/lectures/': {
      id: '/_app/m/library/lectures/'
      path: '/library/lectures'
      fullPath: '/m/library/lectures'
      preLoaderRoute: typeof AppMLibraryLecturesIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/library/podcasts/': {
      id: '/_app/m/library/podcasts/'
      path: '/library/podcasts'
      fullPath: '/m/library/podcasts'
      preLoaderRoute: typeof AppMLibraryPodcastsIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/library/talks/': {
      id: '/_app/m/library/talks/'
      path: '/library/talks'
      fullPath: '/m/library/talks'
      preLoaderRoute: typeof AppMLibraryTalksIndexImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/d/home/articles/$categoryId/$articleId': {
      id: '/_app/d/home/articles/$categoryId/$articleId'
      path: '/home/articles/$categoryId/$articleId'
      fullPath: '/d/home/articles/$categoryId/$articleId'
      preLoaderRoute: typeof AppDHomeArticlesCategoryIdArticleIdImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/lecture-hall/course/activity/$activityId': {
      id: '/_app/d/lecture-hall/course/activity/$activityId'
      path: '/lecture-hall/course/activity/$activityId'
      fullPath: '/d/lecture-hall/course/activity/$activityId'
      preLoaderRoute: typeof AppDLectureHallCourseActivityActivityIdImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/d/lecture-hall/course/lesson/$lessonId': {
      id: '/_app/d/lecture-hall/course/lesson/$lessonId'
      path: '/lecture-hall/course/lesson/$lessonId'
      fullPath: '/d/lecture-hall/course/lesson/$lessonId'
      preLoaderRoute: typeof AppDLectureHallCourseLessonLessonIdImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/m/home/articles/$categoryId/$articleId': {
      id: '/_app/m/home/articles/$categoryId/$articleId'
      path: '/home/articles/$categoryId/$articleId'
      fullPath: '/m/home/articles/$categoryId/$articleId'
      preLoaderRoute: typeof AppMHomeArticlesCategoryIdArticleIdImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/lecture-hall/course/activity/$activityId': {
      id: '/_app/m/lecture-hall/course/activity/$activityId'
      path: '/lecture-hall/course/activity/$activityId'
      fullPath: '/m/lecture-hall/course/activity/$activityId'
      preLoaderRoute: typeof AppMLectureHallCourseActivityActivityIdImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/m/lecture-hall/course/lesson/$lessonId': {
      id: '/_app/m/lecture-hall/course/lesson/$lessonId'
      path: '/lecture-hall/course/lesson/$lessonId'
      fullPath: '/m/lecture-hall/course/lesson/$lessonId'
      preLoaderRoute: typeof AppMLectureHallCourseLessonLessonIdImport
      parentRoute: typeof AppMRouteImport
    }
    '/_app/d/home/articles/$categoryId/': {
      id: '/_app/d/home/articles/$categoryId/'
      path: '/home/articles/$categoryId'
      fullPath: '/d/home/articles/$categoryId'
      preLoaderRoute: typeof AppDHomeArticlesCategoryIdIndexImport
      parentRoute: typeof AppDRouteImport
    }
    '/_app/m/home/articles/$categoryId/': {
      id: '/_app/m/home/articles/$categoryId/'
      path: '/home/articles/$categoryId'
      fullPath: '/m/home/articles/$categoryId'
      preLoaderRoute: typeof AppMHomeArticlesCategoryIdIndexImport
      parentRoute: typeof AppMRouteImport
    }
  }
}

// Create and export the route tree

interface AppDRouteRouteChildren {
  AppDHomeIndexRoute: typeof AppDHomeIndexRoute
  AppDLectureHallIndexRoute: typeof AppDLectureHallIndexRoute
  AppDLibraryIndexRoute: typeof AppDLibraryIndexRoute
  AppDNotificationsIndexRoute: typeof AppDNotificationsIndexRoute
  AppDProfileIndexRoute: typeof AppDProfileIndexRoute
  AppDSettingsIndexRoute: typeof AppDSettingsIndexRoute
  AppDLectureHallCourseCourseIdRoute: typeof AppDLectureHallCourseCourseIdRoute
  AppDLibraryBooksIndexRoute: typeof AppDLibraryBooksIndexRoute
  AppDLibraryImagesIndexRoute: typeof AppDLibraryImagesIndexRoute
  AppDLibraryLecturesIndexRoute: typeof AppDLibraryLecturesIndexRoute
  AppDLibraryPodcastsIndexRoute: typeof AppDLibraryPodcastsIndexRoute
  AppDHomeArticlesCategoryIdArticleIdRoute: typeof AppDHomeArticlesCategoryIdArticleIdRoute
  AppDLectureHallCourseActivityActivityIdRoute: typeof AppDLectureHallCourseActivityActivityIdRoute
  AppDLectureHallCourseLessonLessonIdRoute: typeof AppDLectureHallCourseLessonLessonIdRoute
  AppDHomeArticlesCategoryIdIndexRoute: typeof AppDHomeArticlesCategoryIdIndexRoute
}

const AppDRouteRouteChildren: AppDRouteRouteChildren = {
  AppDHomeIndexRoute: AppDHomeIndexRoute,
  AppDLectureHallIndexRoute: AppDLectureHallIndexRoute,
  AppDLibraryIndexRoute: AppDLibraryIndexRoute,
  AppDNotificationsIndexRoute: AppDNotificationsIndexRoute,
  AppDProfileIndexRoute: AppDProfileIndexRoute,
  AppDSettingsIndexRoute: AppDSettingsIndexRoute,
  AppDLectureHallCourseCourseIdRoute: AppDLectureHallCourseCourseIdRoute,
  AppDLibraryBooksIndexRoute: AppDLibraryBooksIndexRoute,
  AppDLibraryImagesIndexRoute: AppDLibraryImagesIndexRoute,
  AppDLibraryLecturesIndexRoute: AppDLibraryLecturesIndexRoute,
  AppDLibraryPodcastsIndexRoute: AppDLibraryPodcastsIndexRoute,
  AppDHomeArticlesCategoryIdArticleIdRoute:
    AppDHomeArticlesCategoryIdArticleIdRoute,
  AppDLectureHallCourseActivityActivityIdRoute:
    AppDLectureHallCourseActivityActivityIdRoute,
  AppDLectureHallCourseLessonLessonIdRoute:
    AppDLectureHallCourseLessonLessonIdRoute,
  AppDHomeArticlesCategoryIdIndexRoute: AppDHomeArticlesCategoryIdIndexRoute,
}

const AppDRouteRouteWithChildren = AppDRouteRoute._addFileChildren(
  AppDRouteRouteChildren,
)

interface AppMRouteRouteChildren {
  AppMHomeIndexRoute: typeof AppMHomeIndexRoute
  AppMLectureHallIndexRoute: typeof AppMLectureHallIndexRoute
  AppMLibraryIndexRoute: typeof AppMLibraryIndexRoute
  AppMNotificationsIndexRoute: typeof AppMNotificationsIndexRoute
  AppMProfileIndexRoute: typeof AppMProfileIndexRoute
  AppMSettingsIndexRoute: typeof AppMSettingsIndexRoute
  AppMLectureHallCourseCourseIdRoute: typeof AppMLectureHallCourseCourseIdRoute
  AppMLibraryBooksIndexRoute: typeof AppMLibraryBooksIndexRoute
  AppMLibraryImagesIndexRoute: typeof AppMLibraryImagesIndexRoute
  AppMLibraryLecturesIndexRoute: typeof AppMLibraryLecturesIndexRoute
  AppMLibraryPodcastsIndexRoute: typeof AppMLibraryPodcastsIndexRoute
  AppMLibraryTalksIndexRoute: typeof AppMLibraryTalksIndexRoute
  AppMHomeArticlesCategoryIdArticleIdRoute: typeof AppMHomeArticlesCategoryIdArticleIdRoute
  AppMLectureHallCourseActivityActivityIdRoute: typeof AppMLectureHallCourseActivityActivityIdRoute
  AppMLectureHallCourseLessonLessonIdRoute: typeof AppMLectureHallCourseLessonLessonIdRoute
  AppMHomeArticlesCategoryIdIndexRoute: typeof AppMHomeArticlesCategoryIdIndexRoute
}

const AppMRouteRouteChildren: AppMRouteRouteChildren = {
  AppMHomeIndexRoute: AppMHomeIndexRoute,
  AppMLectureHallIndexRoute: AppMLectureHallIndexRoute,
  AppMLibraryIndexRoute: AppMLibraryIndexRoute,
  AppMNotificationsIndexRoute: AppMNotificationsIndexRoute,
  AppMProfileIndexRoute: AppMProfileIndexRoute,
  AppMSettingsIndexRoute: AppMSettingsIndexRoute,
  AppMLectureHallCourseCourseIdRoute: AppMLectureHallCourseCourseIdRoute,
  AppMLibraryBooksIndexRoute: AppMLibraryBooksIndexRoute,
  AppMLibraryImagesIndexRoute: AppMLibraryImagesIndexRoute,
  AppMLibraryLecturesIndexRoute: AppMLibraryLecturesIndexRoute,
  AppMLibraryPodcastsIndexRoute: AppMLibraryPodcastsIndexRoute,
  AppMLibraryTalksIndexRoute: AppMLibraryTalksIndexRoute,
  AppMHomeArticlesCategoryIdArticleIdRoute:
    AppMHomeArticlesCategoryIdArticleIdRoute,
  AppMLectureHallCourseActivityActivityIdRoute:
    AppMLectureHallCourseActivityActivityIdRoute,
  AppMLectureHallCourseLessonLessonIdRoute:
    AppMLectureHallCourseLessonLessonIdRoute,
  AppMHomeArticlesCategoryIdIndexRoute: AppMHomeArticlesCategoryIdIndexRoute,
}

const AppMRouteRouteWithChildren = AppMRouteRoute._addFileChildren(
  AppMRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDRouteRoute: typeof AppDRouteRouteWithChildren
  AppMRouteRoute: typeof AppMRouteRouteWithChildren
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDRouteRoute: AppDRouteRouteWithChildren,
  AppMRouteRoute: AppMRouteRouteWithChildren,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/d': typeof AppDRouteRouteWithChildren
  '/m': typeof AppMRouteRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/register': typeof AuthLayoutRegisterRoute
  '/profile': typeof AppProfileIndexRoute
  '/d/home': typeof AppDHomeIndexRoute
  '/d/lecture-hall': typeof AppDLectureHallIndexRoute
  '/d/library': typeof AppDLibraryIndexRoute
  '/d/notifications': typeof AppDNotificationsIndexRoute
  '/d/profile': typeof AppDProfileIndexRoute
  '/d/settings': typeof AppDSettingsIndexRoute
  '/m/home': typeof AppMHomeIndexRoute
  '/m/lecture-hall': typeof AppMLectureHallIndexRoute
  '/m/library': typeof AppMLibraryIndexRoute
  '/m/notifications': typeof AppMNotificationsIndexRoute
  '/m/profile': typeof AppMProfileIndexRoute
  '/m/settings': typeof AppMSettingsIndexRoute
  '/d/lecture-hall/course/$courseId': typeof AppDLectureHallCourseCourseIdRoute
  '/m/lecture-hall/course/$courseId': typeof AppMLectureHallCourseCourseIdRoute
  '/d/library/books': typeof AppDLibraryBooksIndexRoute
  '/d/library/images': typeof AppDLibraryImagesIndexRoute
  '/d/library/lectures': typeof AppDLibraryLecturesIndexRoute
  '/d/library/podcasts': typeof AppDLibraryPodcastsIndexRoute
  '/m/library/books': typeof AppMLibraryBooksIndexRoute
  '/m/library/images': typeof AppMLibraryImagesIndexRoute
  '/m/library/lectures': typeof AppMLibraryLecturesIndexRoute
  '/m/library/podcasts': typeof AppMLibraryPodcastsIndexRoute
  '/m/library/talks': typeof AppMLibraryTalksIndexRoute
  '/d/home/articles/$categoryId/$articleId': typeof AppDHomeArticlesCategoryIdArticleIdRoute
  '/d/lecture-hall/course/activity/$activityId': typeof AppDLectureHallCourseActivityActivityIdRoute
  '/d/lecture-hall/course/lesson/$lessonId': typeof AppDLectureHallCourseLessonLessonIdRoute
  '/m/home/articles/$categoryId/$articleId': typeof AppMHomeArticlesCategoryIdArticleIdRoute
  '/m/lecture-hall/course/activity/$activityId': typeof AppMLectureHallCourseActivityActivityIdRoute
  '/m/lecture-hall/course/lesson/$lessonId': typeof AppMLectureHallCourseLessonLessonIdRoute
  '/d/home/articles/$categoryId': typeof AppDHomeArticlesCategoryIdIndexRoute
  '/m/home/articles/$categoryId': typeof AppMHomeArticlesCategoryIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/d': typeof AppDRouteRouteWithChildren
  '/m': typeof AppMRouteRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/register': typeof AuthLayoutRegisterRoute
  '/profile': typeof AppProfileIndexRoute
  '/d/home': typeof AppDHomeIndexRoute
  '/d/lecture-hall': typeof AppDLectureHallIndexRoute
  '/d/library': typeof AppDLibraryIndexRoute
  '/d/notifications': typeof AppDNotificationsIndexRoute
  '/d/profile': typeof AppDProfileIndexRoute
  '/d/settings': typeof AppDSettingsIndexRoute
  '/m/home': typeof AppMHomeIndexRoute
  '/m/lecture-hall': typeof AppMLectureHallIndexRoute
  '/m/library': typeof AppMLibraryIndexRoute
  '/m/notifications': typeof AppMNotificationsIndexRoute
  '/m/profile': typeof AppMProfileIndexRoute
  '/m/settings': typeof AppMSettingsIndexRoute
  '/d/lecture-hall/course/$courseId': typeof AppDLectureHallCourseCourseIdRoute
  '/m/lecture-hall/course/$courseId': typeof AppMLectureHallCourseCourseIdRoute
  '/d/library/books': typeof AppDLibraryBooksIndexRoute
  '/d/library/images': typeof AppDLibraryImagesIndexRoute
  '/d/library/lectures': typeof AppDLibraryLecturesIndexRoute
  '/d/library/podcasts': typeof AppDLibraryPodcastsIndexRoute
  '/m/library/books': typeof AppMLibraryBooksIndexRoute
  '/m/library/images': typeof AppMLibraryImagesIndexRoute
  '/m/library/lectures': typeof AppMLibraryLecturesIndexRoute
  '/m/library/podcasts': typeof AppMLibraryPodcastsIndexRoute
  '/m/library/talks': typeof AppMLibraryTalksIndexRoute
  '/d/home/articles/$categoryId/$articleId': typeof AppDHomeArticlesCategoryIdArticleIdRoute
  '/d/lecture-hall/course/activity/$activityId': typeof AppDLectureHallCourseActivityActivityIdRoute
  '/d/lecture-hall/course/lesson/$lessonId': typeof AppDLectureHallCourseLessonLessonIdRoute
  '/m/home/articles/$categoryId/$articleId': typeof AppMHomeArticlesCategoryIdArticleIdRoute
  '/m/lecture-hall/course/activity/$activityId': typeof AppMLectureHallCourseActivityActivityIdRoute
  '/m/lecture-hall/course/lesson/$lessonId': typeof AppMLectureHallCourseLessonLessonIdRoute
  '/d/home/articles/$categoryId': typeof AppDHomeArticlesCategoryIdIndexRoute
  '/m/home/articles/$categoryId': typeof AppMHomeArticlesCategoryIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_app/d': typeof AppDRouteRouteWithChildren
  '/_app/m': typeof AppMRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/auth/_layout/login': typeof AuthLayoutLoginRoute
  '/auth/_layout/register': typeof AuthLayoutRegisterRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/d/home/': typeof AppDHomeIndexRoute
  '/_app/d/lecture-hall/': typeof AppDLectureHallIndexRoute
  '/_app/d/library/': typeof AppDLibraryIndexRoute
  '/_app/d/notifications/': typeof AppDNotificationsIndexRoute
  '/_app/d/profile/': typeof AppDProfileIndexRoute
  '/_app/d/settings/': typeof AppDSettingsIndexRoute
  '/_app/m/home/': typeof AppMHomeIndexRoute
  '/_app/m/lecture-hall/': typeof AppMLectureHallIndexRoute
  '/_app/m/library/': typeof AppMLibraryIndexRoute
  '/_app/m/notifications/': typeof AppMNotificationsIndexRoute
  '/_app/m/profile/': typeof AppMProfileIndexRoute
  '/_app/m/settings/': typeof AppMSettingsIndexRoute
  '/_app/d/lecture-hall/course/$courseId': typeof AppDLectureHallCourseCourseIdRoute
  '/_app/m/lecture-hall/course/$courseId': typeof AppMLectureHallCourseCourseIdRoute
  '/_app/d/library/books/': typeof AppDLibraryBooksIndexRoute
  '/_app/d/library/images/': typeof AppDLibraryImagesIndexRoute
  '/_app/d/library/lectures/': typeof AppDLibraryLecturesIndexRoute
  '/_app/d/library/podcasts/': typeof AppDLibraryPodcastsIndexRoute
  '/_app/m/library/books/': typeof AppMLibraryBooksIndexRoute
  '/_app/m/library/images/': typeof AppMLibraryImagesIndexRoute
  '/_app/m/library/lectures/': typeof AppMLibraryLecturesIndexRoute
  '/_app/m/library/podcasts/': typeof AppMLibraryPodcastsIndexRoute
  '/_app/m/library/talks/': typeof AppMLibraryTalksIndexRoute
  '/_app/d/home/articles/$categoryId/$articleId': typeof AppDHomeArticlesCategoryIdArticleIdRoute
  '/_app/d/lecture-hall/course/activity/$activityId': typeof AppDLectureHallCourseActivityActivityIdRoute
  '/_app/d/lecture-hall/course/lesson/$lessonId': typeof AppDLectureHallCourseLessonLessonIdRoute
  '/_app/m/home/articles/$categoryId/$articleId': typeof AppMHomeArticlesCategoryIdArticleIdRoute
  '/_app/m/lecture-hall/course/activity/$activityId': typeof AppMLectureHallCourseActivityActivityIdRoute
  '/_app/m/lecture-hall/course/lesson/$lessonId': typeof AppMLectureHallCourseLessonLessonIdRoute
  '/_app/d/home/articles/$categoryId/': typeof AppDHomeArticlesCategoryIdIndexRoute
  '/_app/m/home/articles/$categoryId/': typeof AppMHomeArticlesCategoryIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/d'
    | '/m'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/profile'
    | '/d/home'
    | '/d/lecture-hall'
    | '/d/library'
    | '/d/notifications'
    | '/d/profile'
    | '/d/settings'
    | '/m/home'
    | '/m/lecture-hall'
    | '/m/library'
    | '/m/notifications'
    | '/m/profile'
    | '/m/settings'
    | '/d/lecture-hall/course/$courseId'
    | '/m/lecture-hall/course/$courseId'
    | '/d/library/books'
    | '/d/library/images'
    | '/d/library/lectures'
    | '/d/library/podcasts'
    | '/m/library/books'
    | '/m/library/images'
    | '/m/library/lectures'
    | '/m/library/podcasts'
    | '/m/library/talks'
    | '/d/home/articles/$categoryId/$articleId'
    | '/d/lecture-hall/course/activity/$activityId'
    | '/d/lecture-hall/course/lesson/$lessonId'
    | '/m/home/articles/$categoryId/$articleId'
    | '/m/lecture-hall/course/activity/$activityId'
    | '/m/lecture-hall/course/lesson/$lessonId'
    | '/d/home/articles/$categoryId'
    | '/m/home/articles/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/d'
    | '/m'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/profile'
    | '/d/home'
    | '/d/lecture-hall'
    | '/d/library'
    | '/d/notifications'
    | '/d/profile'
    | '/d/settings'
    | '/m/home'
    | '/m/lecture-hall'
    | '/m/library'
    | '/m/notifications'
    | '/m/profile'
    | '/m/settings'
    | '/d/lecture-hall/course/$courseId'
    | '/m/lecture-hall/course/$courseId'
    | '/d/library/books'
    | '/d/library/images'
    | '/d/library/lectures'
    | '/d/library/podcasts'
    | '/m/library/books'
    | '/m/library/images'
    | '/m/library/lectures'
    | '/m/library/podcasts'
    | '/m/library/talks'
    | '/d/home/articles/$categoryId/$articleId'
    | '/d/lecture-hall/course/activity/$activityId'
    | '/d/lecture-hall/course/lesson/$lessonId'
    | '/m/home/articles/$categoryId/$articleId'
    | '/m/lecture-hall/course/activity/$activityId'
    | '/m/lecture-hall/course/lesson/$lessonId'
    | '/d/home/articles/$categoryId'
    | '/m/home/articles/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/_app/d'
    | '/_app/m'
    | '/auth'
    | '/auth/_layout'
    | '/auth/_layout/login'
    | '/auth/_layout/register'
    | '/_app/profile/'
    | '/_app/d/home/'
    | '/_app/d/lecture-hall/'
    | '/_app/d/library/'
    | '/_app/d/notifications/'
    | '/_app/d/profile/'
    | '/_app/d/settings/'
    | '/_app/m/home/'
    | '/_app/m/lecture-hall/'
    | '/_app/m/library/'
    | '/_app/m/notifications/'
    | '/_app/m/profile/'
    | '/_app/m/settings/'
    | '/_app/d/lecture-hall/course/$courseId'
    | '/_app/m/lecture-hall/course/$courseId'
    | '/_app/d/library/books/'
    | '/_app/d/library/images/'
    | '/_app/d/library/lectures/'
    | '/_app/d/library/podcasts/'
    | '/_app/m/library/books/'
    | '/_app/m/library/images/'
    | '/_app/m/library/lectures/'
    | '/_app/m/library/podcasts/'
    | '/_app/m/library/talks/'
    | '/_app/d/home/articles/$categoryId/$articleId'
    | '/_app/d/lecture-hall/course/activity/$activityId'
    | '/_app/d/lecture-hall/course/lesson/$lessonId'
    | '/_app/m/home/articles/$categoryId/$articleId'
    | '/_app/m/lecture-hall/course/activity/$activityId'
    | '/_app/m/lecture-hall/course/lesson/$lessonId'
    | '/_app/d/home/articles/$categoryId/'
    | '/_app/m/home/articles/$categoryId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/about",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/d",
        "/_app/m",
        "/_app/profile/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_app/d": {
      "filePath": "_app/d/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/d/home/",
        "/_app/d/lecture-hall/",
        "/_app/d/library/",
        "/_app/d/notifications/",
        "/_app/d/profile/",
        "/_app/d/settings/",
        "/_app/d/lecture-hall/course/$courseId",
        "/_app/d/library/books/",
        "/_app/d/library/images/",
        "/_app/d/library/lectures/",
        "/_app/d/library/podcasts/",
        "/_app/d/home/articles/$categoryId/$articleId",
        "/_app/d/lecture-hall/course/activity/$activityId",
        "/_app/d/lecture-hall/course/lesson/$lessonId",
        "/_app/d/home/articles/$categoryId/"
      ]
    },
    "/_app/m": {
      "filePath": "_app/m/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/m/home/",
        "/_app/m/lecture-hall/",
        "/_app/m/library/",
        "/_app/m/notifications/",
        "/_app/m/profile/",
        "/_app/m/settings/",
        "/_app/m/lecture-hall/course/$courseId",
        "/_app/m/library/books/",
        "/_app/m/library/images/",
        "/_app/m/library/lectures/",
        "/_app/m/library/podcasts/",
        "/_app/m/library/talks/",
        "/_app/m/home/articles/$categoryId/$articleId",
        "/_app/m/lecture-hall/course/activity/$activityId",
        "/_app/m/lecture-hall/course/lesson/$lessonId",
        "/_app/m/home/articles/$categoryId/"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_layout"
      ]
    },
    "/auth/_layout": {
      "filePath": "auth/_layout.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_layout/login",
        "/auth/_layout/register"
      ]
    },
    "/auth/_layout/login": {
      "filePath": "auth/_layout/login.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/register": {
      "filePath": "auth/_layout/register.tsx",
      "parent": "/auth/_layout"
    },
    "/_app/profile/": {
      "filePath": "_app/profile/index.tsx",
      "parent": "/_app"
    },
    "/_app/d/home/": {
      "filePath": "_app/d/home/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/lecture-hall/": {
      "filePath": "_app/d/lecture-hall/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/library/": {
      "filePath": "_app/d/library/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/notifications/": {
      "filePath": "_app/d/notifications/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/profile/": {
      "filePath": "_app/d/profile/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/settings/": {
      "filePath": "_app/d/settings/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/m/home/": {
      "filePath": "_app/m/home/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/lecture-hall/": {
      "filePath": "_app/m/lecture-hall/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/library/": {
      "filePath": "_app/m/library/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/notifications/": {
      "filePath": "_app/m/notifications/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/profile/": {
      "filePath": "_app/m/profile/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/settings/": {
      "filePath": "_app/m/settings/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/d/lecture-hall/course/$courseId": {
      "filePath": "_app/d/lecture-hall/course/$courseId.tsx",
      "parent": "/_app/d"
    },
    "/_app/m/lecture-hall/course/$courseId": {
      "filePath": "_app/m/lecture-hall/course/$courseId.tsx",
      "parent": "/_app/m"
    },
    "/_app/d/library/books/": {
      "filePath": "_app/d/library/books/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/library/images/": {
      "filePath": "_app/d/library/images/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/library/lectures/": {
      "filePath": "_app/d/library/lectures/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/library/podcasts/": {
      "filePath": "_app/d/library/podcasts/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/m/library/books/": {
      "filePath": "_app/m/library/books/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/library/images/": {
      "filePath": "_app/m/library/images/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/library/lectures/": {
      "filePath": "_app/m/library/lectures/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/library/podcasts/": {
      "filePath": "_app/m/library/podcasts/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/library/talks/": {
      "filePath": "_app/m/library/talks/index.tsx",
      "parent": "/_app/m"
    },
    "/_app/d/home/articles/$categoryId/$articleId": {
      "filePath": "_app/d/home/articles/$categoryId/$articleId.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/lecture-hall/course/activity/$activityId": {
      "filePath": "_app/d/lecture-hall/course/activity/$activityId.tsx",
      "parent": "/_app/d"
    },
    "/_app/d/lecture-hall/course/lesson/$lessonId": {
      "filePath": "_app/d/lecture-hall/course/lesson/$lessonId.tsx",
      "parent": "/_app/d"
    },
    "/_app/m/home/articles/$categoryId/$articleId": {
      "filePath": "_app/m/home/articles/$categoryId/$articleId.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/lecture-hall/course/activity/$activityId": {
      "filePath": "_app/m/lecture-hall/course/activity/$activityId.tsx",
      "parent": "/_app/m"
    },
    "/_app/m/lecture-hall/course/lesson/$lessonId": {
      "filePath": "_app/m/lecture-hall/course/lesson/$lessonId.tsx",
      "parent": "/_app/m"
    },
    "/_app/d/home/articles/$categoryId/": {
      "filePath": "_app/d/home/articles/$categoryId/index.tsx",
      "parent": "/_app/d"
    },
    "/_app/m/home/articles/$categoryId/": {
      "filePath": "_app/m/home/articles/$categoryId/index.tsx",
      "parent": "/_app/m"
    }
  }
}
ROUTE_MANIFEST_END */
